PUT {{baseUrl}}user/customer-languages/6769323770fb18a00573ee90 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}


{
    "language": "6769122a0c2828219e1452e0",

}