POST {{baseUrl}}user/apply-appointment HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
    "detail": "df",
    "company": "67f76ff8b8030049f8ccd6c4",
    "company_user":"67f8e3836db19a4374cde53d",
    "customer":"68034d66523b18a8d1f9914a",
    "appointment_type":"67f76fce65dacd57cd57f231",
    "date": "2025-02-11",
    "services":[
    "67f7735bc6841ce5927c5a28"
    ]
}