POST {{baseUrl}}user/invoices HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{

    "appointment":"67bd7643184ab51f364ab992",
    "company_user":"67b6c69b1427e1b2fe8b550c",
    "detail":"fvfd",
    "date":"2024-03-06",
    "total_amount":"32.4",
    "total_tax":"33.4",
    "total_discount":"43.32"
}