PUT {{baseUrl}}user/customer-documents/6769323770fb18a00573ee90 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}


{
    "document_name": "KJU",
    "document_url":"jhifefe"

}