export const adminPermissions = [
    { name: "Can view company", status: true },
    { name: "Can create company", status: true },
    { name: "Can edit company", status: true },
    { name: "Can delete company", status: true },
    { name: "Can view company user", status: true },
    { name: "Can create company user", status: true },
    { name: "Can edit company user", status: true },
    { name: "Can delete company user", status: true },
    { name: "Can view permission", status: true },
    { name: "Can create permission", status: true },
    { name: "Can edit permission", status: true },
    { name: "Can delete permission", status: true },
    { name: "Can view role", status: true },
    { name: "Can create role", status: true },
    { name: "Can edit role", status: true },
    { name: "Can delete role", status: true },
    { name: "Can view user", status: true },
    { name: "Can create user", status: true },
    { name: "Can edit user", status: true },
    { name: "Can delete user", status: true },
    { name: "Can view appointment", status: true },
    { name: "Can create appointment", status: true },
    { name: "Can edit appointment", status: true },
    { name: "Can delete appointment", status: true },
    { name: "Can view invoice", status: true },
    { name: "Can create invoice", status: true },
    { name: "Can edit invoice", status: true },
    { name: "Can delete invoice", status: true },
    { name: "Can view prescription", status: true },
    { name: "Can create prescription", status: true },
    { name: "Can edit prescription", status: true },
    { name: "Can delete prescription", status: true },
    { name: "Can view company service", status: true },
    { name: "Can create company service", status: true },
    { name: "Can edit company service", status: true },
    { name: "Can delete company service", status: true },
    { name: "Can view customer", status: true },
    { name: "Can create customer", status: true },
    { name: "Can edit customer", status: true },
    { name: "Can delete customer", status: true },
    { name: "Can view customer allergy", status: true },
    { name: "Can create customer allergy", status: true },
    { name: "Can edit customer allergy", status: true },
    { name: "Can delete customer allergy", status: true },
    { name: "Can view customer bank", status: true },
    { name: "Can create customer bank", status: true },
    { name: "Can edit customer bank", status: true },
    { name: "Can delete customer bank", status: true },
]