POST {{baseUrl}}user/appointments HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
    "detail": "df",
    "company": "67a9dd482d1f3d6fe1328d1c",
    "company_user":"67ac45be92c9a7aa500da011",
    "appointment_type":"6777cc8aafb618ca78c3b6ec",
    "date": "2025-02-11 04:00:00 PM",
    "services":[
    "67adcd08da887cd35adcb699"
    ]
}