PUT {{baseUrl}}user/appointments/677ea746b4edd65c0c232ac6 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
    "detail": "mjie",
    "company": "677bb398b3ccd10f2274c88f",
    "company_user":"677e2c7ce956ecff244112b5",
    "customer":"677bad463c13a9a89581c5c2",
    "appointment_type":"6777cc8aafb618ca78c3b6ec",
    "date":"",
}