POST {{baseUrl}}user/customer-banks HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
    "bank_name":"SBI",
    "account_number":"123456",
    "bank_code":"232",
    "status":"true"

}