POST {{baseUrl}}user/customer-medical-covers HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
    "medical_cover_type": "6769122a0c2828219e1452e0",
    "details":"vfdvfwe",
    "start_date":"3",
    "end_date":"3"

}