PUT {{baseUrl}}user/vacancy-apply/680746e8386485ffa3cf6509 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
    "company":"67f777e8c6841ce5927c5bc5",
    "vacancy": "680617e13222ed5fe58c1f72",
}