PUT {{baseUrl}}user/report-documents/678b820504eaef5f0f7efe02 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{

    "appointment": "678a2a9e3c7dc238f9f2fc39",
    "company": "678a2a9e3c7dc238f9f2fc39",
    "company_user": "678a2a9e3c7dc238f9f2fc39",
    "details":"vfdvfwe",
    "url":"grgre",
    "date":"2024-03-06"
}